#!/usr/bin/env bash
# File the conformance-audit findings as GitHub issues.
#
# Usage:
#   ./file-conformance-audit-issues.sh              # dry run: print what would be filed
#   ./file-conformance-audit-issues.sh --apply      # actually create the issues
#   REPO=owner/name ./file-conformance-audit-issues.sh --apply
#
# Requires: gh (authenticated) for --apply; the dry run needs nothing.
# Idempotent: an issue whose exact title already exists (open or closed) is skipped.
# Labels that don't exist on the repo are dropped with a warning rather than failing.

set -euo pipefail

REPO="${REPO:-cerbos/query-plan-adapters}"
APPLY=false
[[ "${1:-}" == "--apply" ]] && APPLY=true

if $APPLY; then
  command -v gh >/dev/null || { echo "gh is required" >&2; exit 1; }
  gh auth status >/dev/null 2>&1 || { echo "run 'gh auth login' first" >&2; exit 1; }
  EXISTING_LABELS="$(gh label list --repo "$REPO" --limit 500 --json name --jq '.[].name')"
  EXISTING_TITLES="$(gh issue list --repo "$REPO" --state all --limit 1000 --json title --jq '.[].title')"
else
  echo "DRY RUN against $REPO — pass --apply to create issues."
  EXISTING_LABELS=""
  EXISTING_TITLES=""
fi

FOOTER=$'\n\n---\n_Found in a static audit of the conformance harnesses. Generated by [Claude Code](https://claude.ai/code)_'

created=0; skipped=0

# file_issue "<title>" "<comma-separated labels>"  (body on stdin)
file_issue() {
  local title="$1" labels="$2" body
  body="$(cat)${FOOTER}"

  if ! $APPLY; then
    printf '\n=== %s\n    labels: %s\n' "$title" "$labels"
    printf '%s\n' "$body" | sed 's/^/    | /'
    return
  fi

  if grep -Fxq -- "$title" <<<"$EXISTING_TITLES"; then
    echo "skip (exists): $title"; skipped=$((skipped + 1)); return
  fi

  local args=() l
  IFS=',' read -ra wanted <<<"$labels"
  for l in "${wanted[@]}"; do
    if grep -Fxq -- "$l" <<<"$EXISTING_LABELS"; then
      args+=(--label "$l")
    else
      echo "  warning: label '$l' not on $REPO, dropping" >&2
    fi
  done

  local url
  url="$(gh issue create --repo "$REPO" --title "$title" --body "$body" "${args[@]}")"
  echo "created: $url"
  created=$((created + 1))
}

# ---------------------------------------------------------------------------
# Corpus-wide
# ---------------------------------------------------------------------------

file_issue "conformance: corpus never plans the root shapes real policies compose to (ALLOW+DENY, multiple ALLOWs)" "needs-triage,conformance" <<'EOF'
## Problem

`conformance/policies/adversarial.yaml` has ~302 rules, **all `EFFECT_ALLOW`**, one role (`USER`), one principal (`u1`), no derived roles, variables or scoped policies. Walking every fixture in `conformance/wire-fixtures/`:

- No root is `and(X, not(Y))` — what a conditional ALLOW plus a conditional DENY composes to.
- No root is `or(and(...), and(...))` — what several conditional ALLOW rules compose to.
- The root `and` fixtures (`filter-as-conjunct`, `nary-and`, `pv-all-unrolled`, `rel-hop-and-root`, `rel-range-hop`) carry no `not` conjunct.
- `and → not` / `or → and` nesting appears only inside `p-deep-nest`, which prisma, mongoose, langchain-chromadb and elasticsearch-java refuse — so for those adapters a negation under a conjunction is never oracle-compared.

`conformance/README.md` ("Hazard classes the corpus missed") says `not-and` is byte-for-byte what a DENY rule composes to. That only holds for a DENY whose condition is `a && b` beside an unconditional ALLOW.

The planner's own composition logic (multiple rules, DENY, derived roles with resource conditions, variables) is never exercised against resource attributes. `evaluation-probe.yaml` has DENY rules and a derived role, but only over principal attributes, so its plans are unconditional. A second planner fold bug like `p-has` would go unnoticed.

## Why it matters

Adapters that special-case the root (convex's DB/post-filter split; the root-only guards `filter-as-conjunct` already caught) are exactly where a composed plan could slip through as an over-grant.

## Proposal

- Add actions whose plans root at `and(X, not(Y))`, `or(and, and)` and `or(X, not(Y))`.
- Add a second resource kind (or policy) with real conditional DENY rules, a derived role with a resource condition, and variables, so the planner's composition output is captured in wire fixtures and compared by every harness.
EOF

file_issue "conformance: aString, aNumber and aBool are never NULL in any seed" "needs-triage,conformance" <<'EOF'
## Problem

In `conformance/seeds.json` (27 seeds), `aString`, `aNumber` and `aBool` are null/absent in **0** rows. NULL witnesses exist only for `aOptionalString` (5 rows), the derived fields and relations.

These are the most-read columns in the corpus (roughly 73 / 56 / 33 fixtures respectively), and dozens of those actions negate (`not`, `ne`). So `!R.attr.aBool`, `R.attr.aNumber != 5`, `!(R.attr.aString == "x")` etc. are never compared against a NULL/missing row — the classic three-valued-logic over-grant this corpus exists to catch. On document stores, `$ne`/`$nor` additionally match documents where the field is absent.

A concrete case already parked in a unit test for want of this: `string(nullBoolColumn) != "true"` (`ent/translate_test.go` / `pgx/translate_test.go`, `TestStringOverABooleanSpellsCELsWords`, bridge tracked by #469).

## Proposal

Add seeds with NULL/missing `aString`, `aNumber`, `aBool` (plus their `derived-fields.json` entries), re-run every harness, and triage divergences per CLAUDE.md "Changing how a condition is translated". Retire the #469 bridge once the corpus carries it.
EOF

file_issue "conformance: no action orders a string column (collation-dependent over-grant)" "needs-triage,conformance" <<'EOF'
## Problem

The only `<`/`>` against a string attribute in `conformance/policies/adversarial.yaml` is the NaN probe (~line 2957). A plain `R.attr.aString > "a"` is never planned.

CEL orders strings by bytes. Adapters emit a plain SQL `<`/`>`, whose result depends on collation. SQLite's default (BINARY) agrees with CEL; PostgreSQL with a locale collation (e.g. `en_US.UTF-8`) does not — `'A' > 'a'` is true there and false in CEL, which returns rows the PDP denies.

The README collation sections (e.g. `sqlalchemy/README.md`, `activerecord/README.md`) cover equality, membership and LIKE, but not ordering.

## Proposal

Add string-ordering actions with case- and accent-discriminating seeds, run them on every store leg (including PostgreSQL under a locale collation to measure the cost, as `ADAPTER_TEST_MYSQL_COLLATION` does for MySQL), and document ordering in each README's collation section.
EOF

file_issue "conformance: assert a non-total oracle for every compared action, not a sample" "needs-triage,conformance,mongoose,convex,prisma,drizzle,ent,pgx" <<'EOF'
## Problem

The degeneracy guard (`conformance/README.md`, "The degeneracy guard") asks for "a handful of representative actions". Several harnesses guard only a sample of what they compare:

| Adapter | Guarded / compared (approx.) |
|---|---|
| ent, pgx | 86 / 235 |
| mongoose | 72 / 202 |
| convex | 105 / 269 |
| prisma | 123 / 172 |
| drizzle | 119 / 236 |

elasticsearch-java, spring-data and langchain-chromadb already guard (nearly) every compared action.

An empty oracle still catches an over-grant (equality fails), but a **total** oracle cannot: an adapter that returns every row passes. For an unguarded action nothing asserts the oracle is non-total. Some are total by construction (`pv-empty-not-exists`, `pv-empty-all`, `ne-map`), which is fine only if listed.

## Proposal

Assert non-total for every oracle-compared action, with an explicit, corpus-level allowlist of actions that are total (or empty) by construction, each with a reason. That also removes the per-harness list drift the README warns about.
EOF

file_issue "conformance: p-has is a live over-grant — link upstream and pin the composed form" "needs-triage,conformance" <<'EOF'
## Problem

`knownDivergences` excludes `p-has` for every adapter: the planner folds `has(R.attr.aOptionalString)` to `KIND_ALWAYS_ALLOWED`, so every adapter returns every row while `check()` denies rows missing the attribute. This is a production over-grant for any consumer whose policy uses `has()`, not a test artifact.

- The `actions.json` entry has no `relatedIssue` / upstream Cerbos link.
- Each adapter README mentions it in one table row; only `spring-data/README.md` gives it a section.
- Only the bare root form is pinned. The composed form — `has(x) && y == 1` silently losing its `has` guard — is not.

## Proposal

- File (or link) the upstream `cerbos/cerbos` planner issue and set `relatedIssue`.
- Add a composed action (`has(x) && <other condition>`) so the tripwire covers the form real policies use.
- Give it a prominent warning in each adapter README rather than a table row.
EOF

# ---------------------------------------------------------------------------
# Fail-open defaults (per adapter)
# ---------------------------------------------------------------------------

file_issue "mongoose, convex: unmapped attributes fall through as raw field paths, so \$ne matches every document" "needs-triage,mongoose,convex" <<'EOF'
## Problem

An attribute with no mapper entry is used verbatim as a field path:

- mongoose: `mongoose/src/mapper.ts` returns `{ path: [reference] }`; `mapper` defaults to `{}`; `nullable` defaults to false.
- convex: `resolveField` in `convex/src/operands.ts` returns the reference verbatim; `isNullableField` defaults to false, and such a field passes `canPushToDb`.

So `R.attr.status != "x"` with a missing or typo'd mapping becomes `{"request.resource.attr.status": {$ne: "x"}}` (or `q.neq(q.field(...), "x")`). The path doesn't exist, `$ne` matches absent fields, and **every document is returned**. `not` via `$nor` has the same problem on any non-`nullable` field that can be absent.

langchain-chromadb is the counter-example: it defaults `required: false` and refuses `$ne`/`$nin` unless the field is declared required.

The corpus can't catch this — every harness maps every field correctly with `nullable` set.

## Proposal

Fail closed: throw on an unmapped reference (or require an explicit pass-through opt-in), and/or default `nullable` to true. Add unit tests for mapping variation (unmapped field, absent field) under the "caller-supplied argument" category.
EOF

file_issue "mongoose: nullAttributeRepresentation \"omitted\" doesn't guard ne/not/nin on absent fields" "needs-triage,mongoose" <<'EOF'
## Problem

`nullAttributeRepresentation: "omitted"` only rejects **null literals** (`assertNullOperandTranslatable`, `mongoose/src/context.ts`). It does not guard `ne` / `not` / `nin` over a field that is NULL or absent and not declared `nullable`.

Under the omitted convention, `R.attr.x != "a"` on such a field makes `check()` raise a missing-attribute error (deny), while `$ne` matches the document — an over-grant. `mongoose/README.md` (~line 87) calls the option "the backstop for mappings that do not declare it", which overstates what it does.

## Proposal

Under `"omitted"`, reject (or null-guard) negated comparisons over fields not declared `nullable`, or correct the README so callers don't rely on it as a backstop. Also consider testing `strictQuery: true`, which strips unknown paths and can turn a filter into `{}`.
EOF

file_issue "Result types let a caller that skips the kind check fail open" "needs-triage,mongoose,langchain-chromadb,convex,ent,pgx" <<'EOF'
## Problem

Several adapters return a result where using the filter without first switching on `kind` returns every row on a denial:

- **mongoose**: `QueryPlanToMongooseResult` is `{ kind, filters? }`, not a discriminated union. On `ALWAYS_DENIED`, `filters` is undefined, and `Model.find(undefined)` returns everything.
- **langchain-chromadb**: `where: undefined` on a denial means all documents.
- **convex**: once `allowPostFilter` is on, nothing in the types forces the caller to apply `postFilter` as well as `filter`; applying `filter` alone over-grants.
- **ent**: `Result.Predicate` is nil for `ALWAYS_DENIED` (and error paths); `s.Where(nil)` leaves WHERE unset. The zero-value `Kind` is `KindAlwaysDenied` and the README/example switch on `Kind`, which mitigates it.
- **pgx**: `Where == ""` on a denial; a builder that skips an empty WHERE over-grants (the example asserts the splice is a syntax error, which helps).

All are documented as "check the kind first", but the types don't enforce it.

## Proposal

Make denial fail closed in the value itself: a discriminated union in TypeScript, a deny-everything filter/predicate (`1 = 0`, `{_id: {$in: []}}`, etc.) instead of undefined/nil/empty, and a combined convex result that can't be half-applied.
EOF

file_issue "prisma: empty and/or becomes {AND: []}, and relation-element nullable is opt-in" "needs-triage,prisma" <<'EOF'
## Problem

1. **Empty boolean operators.** `buildPrismaFilterFromCerbosExpression` (`prisma/src/translate.ts`) maps `and` to `{ AND: operands.map(...) }` with no arity check. An empty `and` becomes `{AND: []}`, which matches everything; an empty `or` becomes `{OR: []}`. drizzle (`filter.ts`) and activerecord throw in the same case. The planner doesn't emit this today, so it's hardening, but it should fail closed. Hierarchy code also returns `{}` in places (`hierarchy.ts`); `{NOT: {}}` under negation is untested.
2. **`nullable` on relation element columns is opt-in** (`prisma/src/index.ts`). Leaving it off a column that can be NULL drops the NULL guard on negated `exists`, `all` and `hasIntersection`-over-`map`, which then return rows with a NULL element the PDP denies. The corpus always declares `nullable: true`, and `prisma/README.md` presents it as a feature, not a hazard.

## Proposal

Throw on zero-operand `and`/`or`; pin `{NOT: {}}` behaviour; consider defaulting relation-element `nullable` to true (or documenting the omission as an over-grant hazard).
EOF

file_issue "elasticsearch-java: type-mismatch guard only runs for fields declared via withScalarTypes" "needs-triage,elasticsearch-java" <<'EOF'
## Problem

`typeMismatchQuery` in `LeafTranslator.java` returns early when the field has no entry in `options.scalarTypes()`. With default options, `R.attr.aNumber == "5"` becomes a `term` query; Elasticsearch coerces `"5"` onto the numeric field and matches it. CEL says false and `check()` denies, so rows the PDP denies are returned.

The corpus runs only with `withScalarTypes` declared (`Corpus.java`), so the default is never oracle-compared. The README hazard row says the adapter "cannot see the mapping" but doesn't point at `withScalarTypes` as the fix.

Related, caller-owned: mapping a string to an analyzed `text` field instead of `keyword` makes `term`/`prefix` match per token and case-insensitively. It's measured in `ElasticsearchSurfaceTest` and documented, but fails silently at runtime.

## Proposal

Either require scalar types (fail closed on an undeclared field used in a scalar comparison) or document `withScalarTypes` prominently as required for correctness.
EOF

file_issue "drizzle: SQLite timestamp literals compare as text without checking the column's type" "needs-triage,drizzle" <<'EOF'
## Problem (suspected — found statically, needs confirming against a real SQLite table)

`valueType: "timestamp"` binds the literal as a normalised RFC 3339 string, stripping a `.000` fraction (`drizzle/src/values.ts`, `normalizeRfc3339Milliseconds`). The column's `dataType` is never checked.

- A text column holding JS `toISOString()` values (`…00.000Z`) compares lexically. Since `'.' < 'Z'`, `timestamp(col) < timestamp("…00Z")` is TRUE at an equal instant — an over-grant.
- For an integer-mode timestamp column, SQLite orders integer < text, so `<` matches every row.

The corpus has the witness (a1 `updatedAt = "…00.000Z"`) but only the field-to-field action reads it, and that action is refused. The ordered thresholds never fall between two spellings of the same instant.

## Proposal

Add a corpus action with a threshold at an instant whose stored spelling differs from the canonical one; check the column's `dataType`/mode in the translator and refuse (or normalise) where the comparison would be lexical.
EOF

file_issue "sqlalchemy: SQLite LIKE pragma undocumented, README overrides untested, empty and_/or_ passes through" "needs-triage,sqlalchemy" <<'EOF'
## Problem

1. **`PRAGMA case_sensitive_like` is not in the README.** The harness sets it (`tests/test_adversarial_conformance.py`); it appears only in a code comment in `_operators.py`. A column collation doesn't change SQLite's LIKE, so a SQLite consumer following the README gets case-insensitive `contains`/`startsWith`/`endsWith` — an over-grant. (`activerecord/README.md` documents the pragma.)
2. **Relation macros are proven against test-only overrides.** `exists`, `all`, `exists_one`, `filter`, `map`, `size`, `hasIntersection`, `in` over related tables come from `OPERATOR_OVERRIDES` in `tests/corpus.py`, not shipped code. Those handle three-valued logic carefully (e.g. `_exists_fn`'s `body.is_(None) → null()` arm). The README's copy-paste overrides are simpler and nothing runs them against the oracle.
3. **Empty `and`/`or`.** `predicate` in `_translator.py` passes `and_(*[])` / `or_(*[])` straight through; an empty `or_()` should be FALSE but can render as an empty clause that `where()` drops. The planner doesn't emit this; activerecord refuses it explicitly.

## Proposal

Document the pragma; either ship the relation overrides as library helpers or run the README's examples through the oracle; throw on zero-operand `and`/`or`.
EOF

file_issue "Default nullAttributeRepresentation is \"explicit\", the permissive convention" "needs-triage,prisma,drizzle,mongoose,sqlalchemy,activerecord,ent,pgx" <<'EOF'
## Problem

Across these adapters, the null-convention option defaults to `explicit` (e.g. `prisma/src/index.ts`, `drizzle/src/index.ts`, `ent/adapter.go`). An application that *omits* NULL attributes from `check()` but keeps the default gets `== null` rendered as `IS NULL`, returning rows the PDP denies. The harnesses demonstrate this deliberately (`null-eq-missing`).

On ent/pgx the harness itself runs with several NULL-able columns (`scope`, `aDouble`, `createdAt`, `updatedAt`, `parent.*`) left at `NullConventionUnset` while its oracle omits their NULLs (`ent/adversarial_test.go`). No current action reaches that combination (e.g. `R.attr.scope == null`), so it's latent rather than failing.

## Proposal

Decide whether the default should be the fail-closed choice (`omitted`, which refuses null-selecting shapes), or require callers to choose explicitly. At minimum, add a corpus action that probes `== null` on a harness column left at the default, so the latent case is exercised.
EOF

# ---------------------------------------------------------------------------
# Store / version coverage
# ---------------------------------------------------------------------------

file_issue "CI doesn't run the corpus on the production stores for sqlalchemy, activerecord and spring-data/Hibernate 7" "needs-triage,sqlalchemy,activerecord,spring-data" <<'EOF'
## Problem

CLAUDE.md: "a store the workflow does not execute is a store the adapter does not cover." Current gaps:

- **sqlalchemy**: all ~242 compared actions run on SQLite (1.4 and 2.x). PostgreSQL runs only the ~21 actions that read a `collection_columns` declaration. MySQL never runs. The PostgreSQL golden SQL is compiled, not executed.
- **activerecord**: SQLite only (`spec/support/database.rb`), and only on AR 8.0 (`.github/workflows/activerecord.yaml`). The MySQL/PostgreSQL branches in `lib/cerbos/active_record/dialect.rb` (`CONCAT`, `CHAR_LENGTH`, `double precision`, …) never execute. (7.1's golden divergence list is pinned empty, so the version gap is small; the store gap is the real one.)
- **spring-data**: H2 runs on Hibernate 6.6 and 7; PostgreSQL and MySQL run only on the baseline ORM. Hibernate 7 × PostgreSQL/MySQL is never exercised.

## Proposal

Add store legs (testcontainers, as drizzle/prisma/ent do) running the full corpus: PostgreSQL and MySQL for sqlalchemy and activerecord; Hibernate 7 × PostgreSQL/MySQL for spring-data. Pin collations as the existing MySQL legs do.
EOF

echo
if $APPLY; then
  echo "done: $created created, $skipped skipped"
else
  echo "dry run complete — re-run with --apply to file."
fi
